### ISSUE TITLE
Game server crashes 8/6/2017

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/gamesvr-srcds-tf2-blindfrag#1]
Game server crashes 8/6/2017
Typical game server crash. Likely due to a conflict between sourcemod and the new tf2 update.

**Comment by dudleycodes** [comment]
Added requested packages to [gamesvr-srcds-tf2](https://github.com/LacledesLAN/gamesvr-srcds-tf2).

@JustinBenedick please see if this issue has been resolved as result.

**Comment by JustinBenedick** [comment]
Did a test, still not resolved

**Comment by dudleycodes** [comment]
This crash is related to the parent image [gamesvr-srcds-tf2](https://github.com/LacledesLAN/gamesvr-srcds-tf2). Issue should be managed on that repository - not this one. Issues on this repository should be specific to this repository.

Closing this issue.
